ADX-1008
fjelltopp/auth0_profile_editor pull request #3
Opened 2023-06-27 15:32 UTC by kforenc

## ADX-1008

Refactoring application so it can be used as a regular flask app. Surprisingly, I needed to use 'python 3.9' since other python versions were missing from images run in minikube.

## Dependency Changes

Added dependencies:
* py-healthcheck
* gevent (was required by minikube to run)

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [ ] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [ ] I have developed these changes in discussion with the appropriate project manager.
- [ ] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [ ] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned at least one reviewer.

2023-06-28 09:16 UTC, tomeksabala requested changes
It should be possible to run it as py3.10 app after publishing a python 3.10 base image. I'll share more info on Slack.

2023-06-28 09:16 UTC, tomeksabala commented on ape/logic.py
> +    log.error(f"Got form with email: {form.email.data}, user_meta: {user_metadata}, user_data: {user_data}, user_id: {user_id}")
probably a log.debug?

2023-06-28 10:05 UTC, kforenc commented on ape/logic.py
> +    log.error(f"Got form with email: {form.email.data}, user_meta: {user_metadata}, user_data: {user_data}, user_id: {user_id}")
Yep, good catch! Fixed.

2023-07-03 08:25 UTC, tomeksabala approved these changes

2023-07-04 14:00 UTC, merged